### ISSUE TITLE
Fix transparency of the characters across the backgrounds 

### ISSUE THREAD

**Issue by RuthAnn1** [Techwise-Team-15/my_pet#47]
## Bug Report

**Description:**
The characters and the background are blending together when the game is played. 

**Steps to Reproduce:**
Easy:  change the background from black to white 🧐

**Expected Behavior:**
The sprite should not be effected by the background.

**Actual Behavior:**
The sprite blends in with the background.

**Code Snippet:**
N/A

**Screenshots/Video:**
N/A

**Environment:**
- Operating System: windows 
- Python version: 3.9.12
- Pygame version:2.3

**Additional Information:**
N/A

**Priority:**
- [ ] Low
- [ ] Medium
- [X] High

**Comment by dinaolmelak** [comment]
### Updated changes by @dinaolmelak July/02/2023
- Fixing the little transparencies within the characters would mean that the png file for the pets ought to be altered.
- I had tried fixing that background with online bg editors. However this is how it turned out for the Raccoon and Rock.
![Image](https://github.com/Techwise-Team-15/my_pet/assets/32272045/c55836e0-56d1-44b4-9e8c-1e976060b677)
![Image](https://github.com/Techwise-Team-15/my_pet/assets/32272045/219bfeab-aa47-49c0-bc99-45227e67ff74)
- Please let me know if you can fix the background of the pets from the original artist @RuthAnn1
